[[pages]]
path = "streamlit_app.py" 
name = "VisÃ£o Geral"
icon = "ğŸ“Š"

[[pages]]
path = "pages/Ativos.py"
name = "GestÃ£o de Ativos"
icon = "ğŸ’»"

[[pages]]
path = "pages/MovimentaÃ§Ãµes.py"
name = "Registrar MovimentaÃ§Ã£o"
icon = "ğŸ”„"

[[pages]]
path = "pages/ManutenÃ§Ãµes.py"
name = "Controle de ManutenÃ§Ãµes"
icon = "ğŸ› ï¸"

[[pages]]
path = "pages/Cadastro_Geral.py"
name = "Cadastros Gerais"
icon = "ğŸ“"

[[pages]]
path = "pages/Cadastro_de_Compras.py"
name = "Registro de Compras"
icon = "ğŸ›’"

[[pages]]
path = "pages/UsuÃ¡rios.py"
name = "GestÃ£o de UsuÃ¡rios"
icon = "ğŸ‘¥"